/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.daos;


import fi.alekster.classical.db.tables.Genre;
import fi.alekster.classical.db.tables.records.GenreRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GenreDao extends DAOImpl<GenreRecord, fi.alekster.classical.db.tables.pojos.Genre, Long> {

    /**
     * Create a new GenreDao without any configuration
     */
    public GenreDao() {
        super(Genre.GENRE, fi.alekster.classical.db.tables.pojos.Genre.class);
    }

    /**
     * Create a new GenreDao with an attached configuration
     */
    public GenreDao(Configuration configuration) {
        super(Genre.GENRE, fi.alekster.classical.db.tables.pojos.Genre.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(fi.alekster.classical.db.tables.pojos.Genre object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.Genre> fetchById(Long... values) {
        return fetch(Genre.GENRE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fi.alekster.classical.db.tables.pojos.Genre fetchOneById(Long value) {
        return fetchOne(Genre.GENRE.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.Genre> fetchByName(String... values) {
        return fetch(Genre.GENRE.NAME, values);
    }
}
