/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.daos;


import fi.alekster.classical.db.tables.Like;
import fi.alekster.classical.db.tables.records.LikeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LikeDao extends DAOImpl<LikeRecord, fi.alekster.classical.db.tables.pojos.Like, Long> {

    /**
     * Create a new LikeDao without any configuration
     */
    public LikeDao() {
        super(Like.LIKE, fi.alekster.classical.db.tables.pojos.Like.class);
    }

    /**
     * Create a new LikeDao with an attached configuration
     */
    public LikeDao(Configuration configuration) {
        super(Like.LIKE, fi.alekster.classical.db.tables.pojos.Like.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(fi.alekster.classical.db.tables.pojos.Like object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.Like> fetchById(Long... values) {
        return fetch(Like.LIKE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fi.alekster.classical.db.tables.pojos.Like fetchOneById(Long value) {
        return fetchOne(Like.LIKE.ID, value);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.Like> fetchByEmail(String... values) {
        return fetch(Like.LIKE.EMAIL, values);
    }

    /**
     * Fetch records that have <code>performance_id IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.Like> fetchByPerformanceId(Long... values) {
        return fetch(Like.LIKE.PERFORMANCE_ID, values);
    }
}
