/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.daos;


import fi.alekster.classical.db.tables.PerformanceGenre;
import fi.alekster.classical.db.tables.records.PerformanceGenreRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PerformanceGenreDao extends DAOImpl<PerformanceGenreRecord, fi.alekster.classical.db.tables.pojos.PerformanceGenre, Record2<Long, Long>> {

    /**
     * Create a new PerformanceGenreDao without any configuration
     */
    public PerformanceGenreDao() {
        super(PerformanceGenre.PERFORMANCE_GENRE, fi.alekster.classical.db.tables.pojos.PerformanceGenre.class);
    }

    /**
     * Create a new PerformanceGenreDao with an attached configuration
     */
    public PerformanceGenreDao(Configuration configuration) {
        super(PerformanceGenre.PERFORMANCE_GENRE, fi.alekster.classical.db.tables.pojos.PerformanceGenre.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, Long> getId(fi.alekster.classical.db.tables.pojos.PerformanceGenre object) {
        return compositeKeyRecord(object.getPerformanceId(), object.getGenreId());
    }

    /**
     * Fetch records that have <code>performance_id IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.PerformanceGenre> fetchByPerformanceId(Long... values) {
        return fetch(PerformanceGenre.PERFORMANCE_GENRE.PERFORMANCE_ID, values);
    }

    /**
     * Fetch records that have <code>genre_id IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.PerformanceGenre> fetchByGenreId(Long... values) {
        return fetch(PerformanceGenre.PERFORMANCE_GENRE.GENRE_ID, values);
    }
}
