/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.daos;


import fi.alekster.classical.db.tables.Venue;
import fi.alekster.classical.db.tables.records.VenueRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VenueDao extends DAOImpl<VenueRecord, fi.alekster.classical.db.tables.pojos.Venue, Long> {

    /**
     * Create a new VenueDao without any configuration
     */
    public VenueDao() {
        super(Venue.VENUE, fi.alekster.classical.db.tables.pojos.Venue.class);
    }

    /**
     * Create a new VenueDao with an attached configuration
     */
    public VenueDao(Configuration configuration) {
        super(Venue.VENUE, fi.alekster.classical.db.tables.pojos.Venue.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(fi.alekster.classical.db.tables.pojos.Venue object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.Venue> fetchById(Long... values) {
        return fetch(Venue.VENUE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fi.alekster.classical.db.tables.pojos.Venue fetchOneById(Long value) {
        return fetchOne(Venue.VENUE.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.Venue> fetchByName(String... values) {
        return fetch(Venue.VENUE.NAME, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.Venue> fetchByDescription(String... values) {
        return fetch(Venue.VENUE.DESCRIPTION, values);
    }
}
