/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.daos;


import fi.alekster.classical.db.tables.WatchdogGenre;
import fi.alekster.classical.db.tables.records.WatchdogGenreRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WatchdogGenreDao extends DAOImpl<WatchdogGenreRecord, fi.alekster.classical.db.tables.pojos.WatchdogGenre, Record2<Long, Long>> {

    /**
     * Create a new WatchdogGenreDao without any configuration
     */
    public WatchdogGenreDao() {
        super(WatchdogGenre.WATCHDOG_GENRE, fi.alekster.classical.db.tables.pojos.WatchdogGenre.class);
    }

    /**
     * Create a new WatchdogGenreDao with an attached configuration
     */
    public WatchdogGenreDao(Configuration configuration) {
        super(WatchdogGenre.WATCHDOG_GENRE, fi.alekster.classical.db.tables.pojos.WatchdogGenre.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Long, Long> getId(fi.alekster.classical.db.tables.pojos.WatchdogGenre object) {
        return compositeKeyRecord(object.getWatchdogId(), object.getGenreId());
    }

    /**
     * Fetch records that have <code>watchdog_id IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.WatchdogGenre> fetchByWatchdogId(Long... values) {
        return fetch(WatchdogGenre.WATCHDOG_GENRE.WATCHDOG_ID, values);
    }

    /**
     * Fetch records that have <code>genre_id IN (values)</code>
     */
    public List<fi.alekster.classical.db.tables.pojos.WatchdogGenre> fetchByGenreId(Long... values) {
        return fetch(WatchdogGenre.WATCHDOG_GENRE.GENRE_ID, values);
    }
}
