/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables;


import fi.alekster.classical.db.Keys;
import fi.alekster.classical.db.Public;
import fi.alekster.classical.db.tables.records.LikeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Like extends TableImpl<LikeRecord> {

    private static final long serialVersionUID = -750912290;

    /**
     * The reference instance of <code>public.like</code>
     */
    public static final Like LIKE = new Like();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LikeRecord> getRecordType() {
        return LikeRecord.class;
    }

    /**
     * The column <code>public.like.id</code>.
     */
    public final TableField<LikeRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.like.email</code>.
     */
    public final TableField<LikeRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>public.like.performance_id</code>.
     */
    public final TableField<LikeRecord, Long> PERFORMANCE_ID = createField("performance_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.like</code> table reference
     */
    public Like() {
        this("like", null);
    }

    /**
     * Create an aliased <code>public.like</code> table reference
     */
    public Like(String alias) {
        this(alias, LIKE);
    }

    private Like(String alias, Table<LikeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Like(String alias, Table<LikeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LikeRecord> getPrimaryKey() {
        return Keys.PK_LIKE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LikeRecord>> getKeys() {
        return Arrays.<UniqueKey<LikeRecord>>asList(Keys.PK_LIKE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Like as(String alias) {
        return new Like(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Like rename(String name) {
        return new Like(name, null);
    }
}
