/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables;


import fi.alekster.classical.db.Keys;
import fi.alekster.classical.db.Public;
import fi.alekster.classical.db.tables.records.PerformanceGenreRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PerformanceGenre extends TableImpl<PerformanceGenreRecord> {

    private static final long serialVersionUID = -1200120563;

    /**
     * The reference instance of <code>public.performance_genre</code>
     */
    public static final PerformanceGenre PERFORMANCE_GENRE = new PerformanceGenre();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PerformanceGenreRecord> getRecordType() {
        return PerformanceGenreRecord.class;
    }

    /**
     * The column <code>public.performance_genre.performance_id</code>.
     */
    public final TableField<PerformanceGenreRecord, Long> PERFORMANCE_ID = createField("performance_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.performance_genre.genre_id</code>.
     */
    public final TableField<PerformanceGenreRecord, Long> GENRE_ID = createField("genre_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.performance_genre</code> table reference
     */
    public PerformanceGenre() {
        this("performance_genre", null);
    }

    /**
     * Create an aliased <code>public.performance_genre</code> table reference
     */
    public PerformanceGenre(String alias) {
        this(alias, PERFORMANCE_GENRE);
    }

    private PerformanceGenre(String alias, Table<PerformanceGenreRecord> aliased) {
        this(alias, aliased, null);
    }

    private PerformanceGenre(String alias, Table<PerformanceGenreRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PerformanceGenreRecord> getPrimaryKey() {
        return Keys.PK_PERFORMANCE_GENRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PerformanceGenreRecord>> getKeys() {
        return Arrays.<UniqueKey<PerformanceGenreRecord>>asList(Keys.PK_PERFORMANCE_GENRE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PerformanceGenreRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PerformanceGenreRecord, ?>>asList(Keys.PERFORMANCE_GENRE__FK_PERFORMANCE_GENRE_PERFORMANCE, Keys.PERFORMANCE_GENRE__FK_PERFORMANCE_GENRE_GENRE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceGenre as(String alias) {
        return new PerformanceGenre(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PerformanceGenre rename(String name) {
        return new PerformanceGenre(name, null);
    }
}
