/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables;


import fi.alekster.classical.db.Keys;
import fi.alekster.classical.db.Public;
import fi.alekster.classical.db.tables.records.WatchdogVenueRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WatchdogVenue extends TableImpl<WatchdogVenueRecord> {

    private static final long serialVersionUID = -1204391995;

    /**
     * The reference instance of <code>public.watchdog_venue</code>
     */
    public static final WatchdogVenue WATCHDOG_VENUE = new WatchdogVenue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WatchdogVenueRecord> getRecordType() {
        return WatchdogVenueRecord.class;
    }

    /**
     * The column <code>public.watchdog_venue.watchdog_id</code>.
     */
    public final TableField<WatchdogVenueRecord, Long> WATCHDOG_ID = createField("watchdog_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.watchdog_venue.venue_id</code>.
     */
    public final TableField<WatchdogVenueRecord, Long> VENUE_ID = createField("venue_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.watchdog_venue</code> table reference
     */
    public WatchdogVenue() {
        this("watchdog_venue", null);
    }

    /**
     * Create an aliased <code>public.watchdog_venue</code> table reference
     */
    public WatchdogVenue(String alias) {
        this(alias, WATCHDOG_VENUE);
    }

    private WatchdogVenue(String alias, Table<WatchdogVenueRecord> aliased) {
        this(alias, aliased, null);
    }

    private WatchdogVenue(String alias, Table<WatchdogVenueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WatchdogVenueRecord> getPrimaryKey() {
        return Keys.PK_WATCHDOG_VENUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WatchdogVenueRecord>> getKeys() {
        return Arrays.<UniqueKey<WatchdogVenueRecord>>asList(Keys.PK_WATCHDOG_VENUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<WatchdogVenueRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WatchdogVenueRecord, ?>>asList(Keys.WATCHDOG_VENUE__FK_WATCHDOG_VENUE_WATCHDOG, Keys.WATCHDOG_VENUE__FK_WATCHDOG_VENUE_VENUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WatchdogVenue as(String alias) {
        return new WatchdogVenue(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WatchdogVenue rename(String name) {
        return new WatchdogVenue(name, null);
    }
}
