/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements Serializable {

    private static final long serialVersionUID = 17226588;

    private Long   id;
    private String name;
    private String wikipediaLink;

    public Author() {}

    public Author(Author value) {
        this.id = value.id;
        this.name = value.name;
        this.wikipediaLink = value.wikipediaLink;
    }

    public Author(
        Long   id,
        String name,
        String wikipediaLink
    ) {
        this.id = id;
        this.name = name;
        this.wikipediaLink = wikipediaLink;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getWikipediaLink() {
        return this.wikipediaLink;
    }

    public void setWikipediaLink(String wikipediaLink) {
        this.wikipediaLink = wikipediaLink;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Author (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(wikipediaLink);

        sb.append(")");
        return sb.toString();
    }
}
