/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements Serializable {

    private static final long serialVersionUID = -1596995678;

    private Long   id;
    private String name;
    private String description;
    private String wikipediaLink;
    private String imageUrl;

    public Author() {}

    public Author(Author value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.wikipediaLink = value.wikipediaLink;
        this.imageUrl = value.imageUrl;
    }

    public Author(
        Long   id,
        String name,
        String description,
        String wikipediaLink,
        String imageUrl
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.wikipediaLink = wikipediaLink;
        this.imageUrl = imageUrl;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getWikipediaLink() {
        return this.wikipediaLink;
    }

    public void setWikipediaLink(String wikipediaLink) {
        this.wikipediaLink = wikipediaLink;
    }

    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Author (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(wikipediaLink);
        sb.append(", ").append(imageUrl);

        sb.append(")");
        return sb.toString();
    }
}
