/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Credential implements Serializable {

    private static final long serialVersionUID = -1096191662;

    private String email;
    private String password;

    public Credential() {}

    public Credential(Credential value) {
        this.email = value.email;
        this.password = value.password;
    }

    public Credential(
        String email,
        String password
    ) {
        this.email = email;
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Credential (");

        sb.append(email);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }
}
