/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gig implements Serializable {

    private static final long serialVersionUID = -592812009;

    private Long      id;
    private Long      venueId;
    private String    name;
    private String    description;
    private Timestamp timestamp;
    private Integer   duration;

    public Gig() {}

    public Gig(Gig value) {
        this.id = value.id;
        this.venueId = value.venueId;
        this.name = value.name;
        this.description = value.description;
        this.timestamp = value.timestamp;
        this.duration = value.duration;
    }

    public Gig(
        Long      id,
        Long      venueId,
        String    name,
        String    description,
        Timestamp timestamp,
        Integer   duration
    ) {
        this.id = id;
        this.venueId = venueId;
        this.name = name;
        this.description = description;
        this.timestamp = timestamp;
        this.duration = duration;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVenueId() {
        return this.venueId;
    }

    public void setVenueId(Long venueId) {
        this.venueId = venueId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public Integer getDuration() {
        return this.duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Gig (");

        sb.append(id);
        sb.append(", ").append(venueId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(duration);

        sb.append(")");
        return sb.toString();
    }
}
