/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.records;


import fi.alekster.classical.db.tables.PerformanceGenre;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PerformanceGenreRecord extends UpdatableRecordImpl<PerformanceGenreRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 132543059;

    /**
     * Setter for <code>public.performance_genre.performance_id</code>.
     */
    public void setPerformanceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.performance_genre.performance_id</code>.
     */
    public Long getPerformanceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.performance_genre.genre_id</code>.
     */
    public void setGenreId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.performance_genre.genre_id</code>.
     */
    public Long getGenreId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PerformanceGenre.PERFORMANCE_GENRE.PERFORMANCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return PerformanceGenre.PERFORMANCE_GENRE.GENRE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPerformanceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getGenreId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceGenreRecord value1(Long value) {
        setPerformanceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceGenreRecord value2(Long value) {
        setGenreId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceGenreRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PerformanceGenreRecord
     */
    public PerformanceGenreRecord() {
        super(PerformanceGenre.PERFORMANCE_GENRE);
    }

    /**
     * Create a detached, initialised PerformanceGenreRecord
     */
    public PerformanceGenreRecord(Long performanceId, Long genreId) {
        super(PerformanceGenre.PERFORMANCE_GENRE);

        set(0, performanceId);
        set(1, genreId);
    }
}
