/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.records;


import fi.alekster.classical.db.tables.Performance;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PerformanceRecord extends UpdatableRecordImpl<PerformanceRecord> implements Record8<Long, Long, Long, String, String, String, String, String> {

    private static final long serialVersionUID = 462889751;

    /**
     * Setter for <code>public.performance.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.performance.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.performance.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.performance.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.performance.gig_id</code>.
     */
    public void setGigId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.performance.gig_id</code>.
     */
    public Long getGigId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.performance.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.performance.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.performance.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.performance.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.performance.conductor</code>.
     */
    public void setConductor(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.performance.conductor</code>.
     */
    public String getConductor() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.performance.players</code>.
     */
    public void setPlayers(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.performance.players</code>.
     */
    public String getPlayers() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.performance.youtube_id</code>.
     */
    public void setYoutubeId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.performance.youtube_id</code>.
     */
    public String getYoutubeId() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Long, String, String, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Long, String, String, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Performance.PERFORMANCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Performance.PERFORMANCE.AUTHOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Performance.PERFORMANCE.GIG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Performance.PERFORMANCE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Performance.PERFORMANCE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Performance.PERFORMANCE.CONDUCTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Performance.PERFORMANCE.PLAYERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Performance.PERFORMANCE.YOUTUBE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getGigId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getConductor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPlayers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getYoutubeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceRecord value2(Long value) {
        setAuthorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceRecord value3(Long value) {
        setGigId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceRecord value6(String value) {
        setConductor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceRecord value7(String value) {
        setPlayers(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceRecord value8(String value) {
        setYoutubeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceRecord values(Long value1, Long value2, Long value3, String value4, String value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PerformanceRecord
     */
    public PerformanceRecord() {
        super(Performance.PERFORMANCE);
    }

    /**
     * Create a detached, initialised PerformanceRecord
     */
    public PerformanceRecord(Long id, Long authorId, Long gigId, String name, String description, String conductor, String players, String youtubeId) {
        super(Performance.PERFORMANCE);

        set(0, id);
        set(1, authorId);
        set(2, gigId);
        set(3, name);
        set(4, description);
        set(5, conductor);
        set(6, players);
        set(7, youtubeId);
    }
}
