/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.records;


import fi.alekster.classical.db.tables.WatchdogAuthor;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WatchdogAuthorRecord extends UpdatableRecordImpl<WatchdogAuthorRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1010531302;

    /**
     * Setter for <code>public.watchdog_author.watchdog_id</code>.
     */
    public void setWatchdogId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.watchdog_author.watchdog_id</code>.
     */
    public Long getWatchdogId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.watchdog_author.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.watchdog_author.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return WatchdogAuthor.WATCHDOG_AUTHOR.WATCHDOG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return WatchdogAuthor.WATCHDOG_AUTHOR.AUTHOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getWatchdogId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WatchdogAuthorRecord value1(Long value) {
        setWatchdogId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WatchdogAuthorRecord value2(Long value) {
        setAuthorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WatchdogAuthorRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WatchdogAuthorRecord
     */
    public WatchdogAuthorRecord() {
        super(WatchdogAuthor.WATCHDOG_AUTHOR);
    }

    /**
     * Create a detached, initialised WatchdogAuthorRecord
     */
    public WatchdogAuthorRecord(Long watchdogId, Long authorId) {
        super(WatchdogAuthor.WATCHDOG_AUTHOR);

        set(0, watchdogId);
        set(1, authorId);
    }
}
