/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db.tables.records;


import fi.alekster.classical.db.tables.WatchdogGenre;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WatchdogGenreRecord extends UpdatableRecordImpl<WatchdogGenreRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1312630000;

    /**
     * Setter for <code>public.watchdog_genre.watchdog_id</code>.
     */
    public void setWatchdogId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.watchdog_genre.watchdog_id</code>.
     */
    public Long getWatchdogId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.watchdog_genre.genre_id</code>.
     */
    public void setGenreId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.watchdog_genre.genre_id</code>.
     */
    public Long getGenreId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return WatchdogGenre.WATCHDOG_GENRE.WATCHDOG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return WatchdogGenre.WATCHDOG_GENRE.GENRE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getWatchdogId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getGenreId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WatchdogGenreRecord value1(Long value) {
        setWatchdogId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WatchdogGenreRecord value2(Long value) {
        setGenreId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WatchdogGenreRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WatchdogGenreRecord
     */
    public WatchdogGenreRecord() {
        super(WatchdogGenre.WATCHDOG_GENRE);
    }

    /**
     * Create a detached, initialised WatchdogGenreRecord
     */
    public WatchdogGenreRecord(Long watchdogId, Long genreId) {
        super(WatchdogGenre.WATCHDOG_GENRE);

        set(0, watchdogId);
        set(1, genreId);
    }
}
