/*
 * This file is generated by jOOQ.
*/
package fi.alekster.classical.db;


import fi.alekster.classical.db.tables.Author;
import fi.alekster.classical.db.tables.Databasechangelog;
import fi.alekster.classical.db.tables.Databasechangeloglock;
import fi.alekster.classical.db.tables.Gig;
import fi.alekster.classical.db.tables.Performance;
import fi.alekster.classical.db.tables.Venue;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = fi.alekster.classical.db.tables.Author.AUTHOR;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = fi.alekster.classical.db.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = fi.alekster.classical.db.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.gig</code>.
     */
    public static final Gig GIG = fi.alekster.classical.db.tables.Gig.GIG;

    /**
     * The table <code>public.performance</code>.
     */
    public static final Performance PERFORMANCE = fi.alekster.classical.db.tables.Performance.PERFORMANCE;

    /**
     * The table <code>public.venue</code>.
     */
    public static final Venue VENUE = fi.alekster.classical.db.tables.Venue.VENUE;
}
